export const Colors = {
  primary: '#0043c8',
  primaryContainer: '#0057ff',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#e5e8ff',
  secondary: '#4f5f78',
  secondaryContainer: '#d0e1fe',
  onSecondaryContainer: '#53637c',
  secondaryFixed: '#d4e3ff',
  onSecondaryFixed: '#0a1c32',
  tertiary: '#952c00',
  tertiaryContainer: '#be3b00',
  onTertiaryContainer: '#ffe4dc',
  tertiaryFixed: '#ffdbd0',
  onTertiaryFixed: '#390c00',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  surface: '#faf8ff',
  surfaceBright: '#faf8ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f2ff',
  surfaceContainer: '#ededfa',
  surfaceContainerHigh: '#e7e7f5',
  surfaceContainerHighest: '#e1e1ef',
  surfaceDim: '#d9d9e6',
  onSurface: '#191b25',
  onSurfaceVariant: '#434656',
  outline: '#737688',
  outlineVariant: '#c3c5d9',
  background: '#faf8ff',
  onBackground: '#191b25',
  inverseSurface: '#2e303a',
  inverseOnSurface: '#f0f0fd',
  inversePrimary: '#b6c4ff',
  primaryFixed: '#dce1ff',
  primaryFixedDim: '#b6c4ff',
};

export const Fonts = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  semiBold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
  extraBold: 'Inter_800ExtraBold',
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const BorderRadius = {
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  full: 9999,
};
